name = "LearningAlgebraicVarieties"
uuid = "99c59dee-8a25-45ad-b85d-0d599d702169"
authors = ["PBrdng <pbrdng@gmail.com>"]
version = "0.3.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Eirene = "9c0f25c4-2ca1-5870-89f6-52640788da1d"
FixedPolynomials = "3dd14ad9-0029-526e-86e9-8aa0bdd2ab0d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Clustering = "0.15.6"
Colors = "0.12.10"
Combinatorics = "1.0"
DynamicPolynomials = "0.3.21"
Eirene = "1.4"
FixedPolynomials = "0.4.0"
LinearAlgebra = "1.10"
MultivariatePolynomials = "0.3.18"
Plots = "1.39"
RowEchelon = "0.2.1"
Statistics = "1.10"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
