[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
FixedPolynomials = "3dd14ad9-0029-526e-86e9-8aa0bdd2ab0d"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
